sample/app/github/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from views import *

urlpatterns = patterns('',
    url(r'social/logout', 'app.github.views.logout', name='app_github_logout'),
    url(r'social/', include('social_auth.urls')),                           #: django-social-auth フレームワーク
    url(r'gist/(?P<gid>\d*)(?P<command>.*)', GistView.as_view(), name="app_github_gist"),
    url(r'', 'app.github.views.default',name='app_github_default' ),
)

sample/app/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'app.views.home', name='home'),
    url(r'^github/', include('app.github.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

sample/app/github/models.py
from django.db import models
from django.contrib.auth.models import User

from api import Gist as GistApi, get_social_user

class Gist(models.Model):
    user    = models.ForeignKey(User)
    gid     = models.CharField(u'Gist ID',max_length=100,null=True,blank=True,default=None)
    filename = models.CharField(u'File Name',max_length=100)
    contents = models.TextField(u'Contents') 
    response = None

    def save(self,*args,**kwargs):
        ''' '''
        if self.gid == None:
            ''' create '''
            client = GistApi(social_user = self.social_auth )
            client.add_file(self.filename,self.contents )
            self.response = client.create()

    @property
    def social_auth(self):
        return self.user and get_social_user(self.user) 

    class Meta:
        abstract=True

sample/app/github/forms.py
# -*- coding: utf-8 -*- from django import forms

from django import forms
from django.conf import settings
from django.core.files import File
from django.core.paginator import Paginator

from models import *

import os
import uuid
import re

class GistItemForm(forms.ModelForm):

    def __init__(self,*args,**kwargs):
        super(GistItemForm,self).__init__(*args,**kwargs)

    def save(self,*args,**kwargs):
        try:
            super(GistItemForm,self).save(*args,**kwargs )
        except:
            self.instance.save()

    def to_preview(self):
        ''' フォームのアイテムを全てhiddeに変更する 
        '''
        for k,f in self.fields.items():
            if str(type(f)).find('Multi') >0: 
                f.widget = forms.MultipleHiddenInput() 

            elif isinstance(f.widget, forms.HiddenInput ) == False:
                f.widget = forms.HiddenInput() 

    class Meta:
        model= Gist
        exclude = ['gid','user',]
        widgets = {
            'usage': forms.RadioSelect(),
        }

class GistListForm(forms.Form):
    pass

sample/app/github/views.py
# -*- coding: utf-8 -*-
from django import template
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib import auth


from social_auth.decorators import dsa_view
from django.utils.timezone import now
from datetime import datetime

from models import *
from forms import *

def default(request,*args,**kwargs):
    ''' default page '''
    return render_to_response( 'github/default.html',
        {  
        },
        context_instance=template.RequestContext(request),)

def logout(request):
    ''' logout '''
    auth.logout(request)
    return  HttpResponseRedirect( reverse('app_github_default'))

def pipeline_binding(*args,**kwargs):
    ''' パイプライン: ソーシャルユーザーを受け入れるかどうかの判断
    '''
    request = kwargs.get('request',None)
    assert request != None
    assert kwargs['github'] == True

    user = kwargs.get('user',None)
    social_user = kwargs.get('social_user',None)
    uid = kwargs.get('uid',None)
    is_new = kwargs.get('is_new',None)

    #:ゲート(last)を判定
    last = request.session.get('last',None)
    if last != None and (now() - last ).total_seconds() < 100:
        return None  #:つぎへ

    #:ゲートをセット
    request.session['last'] = now()

    #:表示メッセージ切り替え
    if request.user.is_authenticated():
        message = u"現在のユーザーにバインド"
    elif user == None and social_user ==None:
        message = u"新規登録"
    else:
        message = u"ソーシャルアカウントでログイン"

    #: UI
    return render_to_response( 'github/binding.html',
            { 
                'is_authenticated': request.user.is_authenticated(),
                'is_new': is_new,
                'user':user,  
                'social_user': social_user,
                'uid':uid,
                'message': message,
            } , 
            context_instance=template.RequestContext(request),)
     

from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView


class GistView(FormView):
    template_name = "github/gist/item.html"
    form_class = GistItemForm

    def dispatch(self, request, *args, **kwargs):
        #:
        if kwargs['command'] in [None,'list','']:
            #:一覧
            kwargs['command'] = 'list'
            self.form_class = GistListForm
        else:
            kwargs['command'] = kwargs['command'].replace('/','')
            
        self.template_name = "github/gist/%(command)s.html" % kwargs

        try:
            res =  super(GistView,self).dispatch(request,*args,**kwargs)

            return res
        except Exception,e:
            return self.render_to_response(self.get_context_data(
                        form=self.get_form(self.form_class)
                    ))

    def get_form_kwargs(self):  #:API
        ''' '''
        res =  super(GistView,self).get_form_kwargs()
        #: ここで強制的にデータを変換させたりとか 
        return res

    def get_form(self, form_class): 
        ''' 
        '''
        vals =  self.get_form_kwargs()   #:GET,POST & FILES
        vals['initial'] = {'user': self.request.user, }
        if self.kwargs['command'] != None:
            form_class = GistItemForm

        try: 
            ret = form_class( ** vals )
            return ret
        except Exception,e:
#            log.debug(str(e))	
            print str(e)
            raise e

        return form_class()          #:TODO: should be error?      

    def get_context_data(self, **kwargs):
        ''' コンテキストデータ '''
        ret = super(GistView,self).get_context_data(**kwargs)
        #: 追加はここで
        form = kwargs.get('form',None)
        if form and form.instance and form.instance.response:
            ret['gist_response'] = form.instance.response.json 
        return ret
    
    def form_valid(self, form):
        ''' ''' 
        try:
            action = self.request.POST.get('action',u'edit') 
            form.instance.user = self.request.user
            { 
                "save": lambda : form.save(),
                "edit": lambda : True,
                "preview": lambda : form.to_preview(),
            }[action](); 
            
        except Exception,e:
            action = "edit"
            print str(e)

        self.template_name = "github/gist/%s.html" % action
                
        return self.render_to_response(self.get_context_data(
                        form = form
                    ))
        
    def form_invalid(self, form):
        return super(GistView ,self).form_invalid(form)

sample/app/github/templates/github/account/binding.html
{% extends "base.html" %}

{% block content %}

<h1>Binding Your Social Identity</h1>

{% if is_authenticated %}

<form method="post" action="{% url socialauth_complete backend='github' %}" >
  <input type="submit" name="bind" value="current" /> <br/>
  <input type="submit" name="bind" value="new" /> <br/>
  <hr/>
  username :<input type="text" name="username" /> <br/>
  password :<input type="password" name="password" /> <br/>
  <input type="submit" name="bind" value="other" /> <br/>
</form>
{% else %}
<form method="post" action="{% url socialauth_complete backend='github' %}" >
  <input type="submit" name="bind" value="new" /> <br/>
  <input type="submit" name="bind" value="other" /> <br/>
</form>

{% endif %}

{% endblock %}

sample/app/github/templates/github/binding.html
{% extends "base.html" %}

{% block content %}

<h1>Binding Your Social Identity</h1>

<a href="{% url socialauth_complete backend='github' %}" >{{ message }}
{% if user %}( {{user}} ) {% endif %}
</a>
<br/>
<a href="{% url app_github_logout %}">取り消し(ログオフ)</a> 

{% endblock %}

sample/app/github/templates/github/default.html
{% extends "base.html"%}
{% block content %}
{% endblock %}

sample/app/github/templates/github/gist/create.html
{% extends "base.html" %}

{% block style %}
<style>
div.form-row { clear:both; }
div.form-col { float:left; }
div.col-name { width:100px; }
div.col-value{ width:100px; }
</style>
{% endblock %}

{% block content %}

<h1>Edit Gist</h1>
{% if form %}
<div id="form">
<form method="post" /> {% csrf_token %}
<div class="form-row">
    <div class="form-col col-name"><label for="id_filename">ファイル名</label></div>
    <div class="form-col cal-value">{{ form.filename }}</div>
</div>
<div class="form-row">
    <div class="form-col col-name"><label for="id_contents">ファイル内容</label></div>
    <div class="form-col col-value">{{ form.contents }}</div>
</div>
<div class="form-row">
    <div class="form-col col-name">&nbsp;</div>
    <div class="form-col col-value">
    <input type="submit" name="action" value="save" />
    </div>
</div>
<div class="form-row">
    <div class="form-col col-name">&nbsp;</div>
    <div class-"form-col col-value">
    <span>１ファイルしか対応していません。。。</span>
    </div>
</div>
</form>
</div>
{% endif %}

{% endblock %}

sample/app/github/templates/github/gist/edit.html
{% extends "base.html" %}

{% block content %}

<h1>Edit Gist</h1>
{% if form %}
    {{ form }}
    <input type="submit" name="action" value="save" />
{% endif %}

{% endblock %}

sample/app/github/templates/github/gist/save.html
{% extends "base.html" %}

{% block content %}

<h1>Git Created</h1>

{% if gist_response %}
    <a href="{{ gist_response.html_url }}">{{ gist_response.html_url }} </a>
{% endif %}
{% endblock %}

sample/app/templates/base.html
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    {% block style %}{% endblock %}
  </head>
  <body>
    <div id="social">
        <div>
        {% if request.user.is_authenticated  and github_user %}
            {{ request.user }} 
            <a href="{% url app_github_gist gid='' command='create'  %}">New Gist</a> 
            <a href="{% url app_github_logout %}">ログアウト</a>
        {% else %}
            <a href="{% url socialauth_begin backend='github' %}">Github</a>
        {% endif %}
        </div>
    </div>
    <div id="contents">
     {% block content %}
        <!-- something here -->
     {% endblock %}
    </div>
  </body>
</html>